In [1]:
import numpy as np


In [2]:
import numpy as np
print(np.__version__)

2.2.3


In [3]:
list = [10, 20, 30, 40, 50]
arr = np.array(list)
print(arr)
print('Type:', type(arr))
print('Shape',arr.shape)

[10 20 30 40 50]
Type: <class 'numpy.ndarray'>
Shape (5,)


In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1[0])
print(arr1[0][2])


[[1 2 3]
 [4 5 6]]
(2, 3)
6
[1 2 3]
3


In [6]:
arr1=np.zeros([2,3])
print(arr1)
print(arr1[0][1])

[[0. 0. 0.]
 [0. 0. 0.]]
0.0


In [10]:
arr2=np.ones((3,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr3=np.arange(1,10,3)
print(arr3)

[1 4 7]


In [14]:
sample=np.array([np.arange(1,10,3),np.arange(2,10,3)])
print(sample)

[[1 4 7]
 [2 5 8]]


In [19]:
import numpy as np
purchase=np.array([
    [200,150,100],
    [300,250,400],
    [100,200,150],
    [500,600,550],
    [50,80,100]
])
total_spend = purchase.sum(axis=1)
average_spend = purchase.mean(axis=1)
print("Total Spend:",total_spend)
print("Average Spend:",average_spend)
print(max(average_spend))

Total Spend: [ 450  950  450 1650  230]
Average Spend: [150.         316.66666667 150.         550.          76.66666667]
550.0


In [22]:
#2x+3y=8
#4x+y=10
import numpy as np
#coeffient of variables 
A=np.array([[2,3],[4,1]])
#constants on the rhs
B=np.array([8,10])
#Solve for x and y 
solution=np.linalg.solve(A,B)
print("Solution(x,y):",solution)

Solution(x,y): [2.2 1.2]


In [23]:
sales=np.array([1000,2000,1800,1500,1900,2000,1750,6476,8484,2344])
total_sales=sum(sales)
print(total_sales)

29254


In [24]:
average_sales=np.mean(sales)
print(average_sales)

2925.4


In [25]:
print(max(sales))

8484


In [28]:
print(sales)

[1000 2000 1800 1500 1900 2000 1750 6476 8484 2344]


In [29]:
print(min(sales))

1000


In [27]:
for num in sales:
    increase = 1.1 * num
    print(increase)

1100.0
2200.0
1980.0000000000002
1650.0000000000002
2090.0
2200.0
1925.0000000000002
7123.6
9332.400000000001
2578.4


In [ ]:
import numpy as np